# Generated by Django 4.1.7 on 2023-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='Title')),
                ('event_date', models.DateTimeField(verbose_name='Date')),
                ('location', models.CharField(max_length=150, verbose_name='Place')),
                ('description', models.TextField(blank=True, max_length=900, verbose_name='Description')),
                ('attendees', models.ManyToManyField(blank=True, to='party.followers')),
            ],
        ),
    ]
