# Generated by Django 4.1.7 on 2023-04-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Title',
            field=models.CharField(max_length=150, verbose_name='Event Name'),
        ),
    ]
